### ISSUE TITLE
Lag Lua :D 

### ISSUE THREAD

**Issue by DelisWTF** [Ascerr/Lua-Scripts#10]
Bro, all my computers are all always with over 1000 2000 ms, and it make the bot didn't work like it normally does, I mean every time it tryes to pick up blank runes and I'm lagged and didnt pick the rune at time the bot makes ancreo lux (utevo lux in medivia) to burn mana, so I was wondering if u could make a Lua that just make the bot work like always but "slower" I guess just to have time to pick up blank runes because this happen a lot times to me and at the end of the day if lag it's to much I waste many many mana.

**Comment by Ascerr** [comment]
Hello,

You mean the game connection ping? You can set cast spell every time
(in seconds)

https://github.com/Ascerr/Lua-Scripts/blob/master/Cast Spell On Time.lua

2021-05-30 14:45 GMT+02:00, DelisWTF ***@***.***>:

**Comment by DelisWTF** [comment]
Actually that script works great but the only problem it's that doesn't pick up blank runes from backpack when it makes the spell, could u make it pick up a blank runes and then it make the spell?

**Comment by Ascerr** [comment]
I have made changes in this lua script you can now enable wearing blanks.

local WEAR_BLANK_RUNE = false       -- wear blank rune before casting spell
local BLANK_RUNE_ID = 2260          -- id of blank rune

2021-05-31 16:50 GMT+02:00, DelisWTF ***@***.***>:

**Comment by DelisWTF** [comment]
I'm not sure at all if it was that but I change false to true in this line
local WEAR_BLANK_RUNE = false (true)

And it start wearing blanks because it wasn't doing it, now its working great thanks again bro :3
