### ISSUE TITLE
heal with hotkey

### ISSUE THREAD

**Issue by well1165** [Ascerr/Lua-Scripts#25]
Hello, I don't know if this is the right place, but I recently started using the bot, and I would like to for example "when I have 50% health, then use press F5" which is the hotkey of my potion. if someone please can help me, I even tried to see in the list of examples, and there were none like this (or I didn't find them)

**Comment by Ascerr** [comment]
Hello,

You can use this lua script:
https://github.com/Ascerr/Lua-Scripts/blob/master/Healing%20-%20Key%20simulate.lua

pt., 7 cze 2024 o 12:04 well1165 ***@***.***> napisał(a):
