### ISSUE TITLE
Alert when drops legendarny Item.

### ISSUE THREAD

**Issue by Lewy207** [Ascerr/Lua-Scripts#29]
Hello,
I use this link with script
https://github.com/Ascerr/Lua-Scripts/blob/beb01b79e76b02c127a11e9209d6400432540b72/Alarm%20on%20Rarity%20Orange%20Message.lua#L4

I change in scrpit rarity for legendary but not work. 
Any sugestions? 
![IMG_20240611_181211](https://github.com/Ascerr/Lua-Scripts/assets/169442582/7d2f473d-7a14-4822-a8bc-5de0781c779a)

**Comment by Ascerr** [comment]
Hello

First you need to discover i this message about legendary i possible to
detect this message, add as new line: 13 this:

print("proxy: " .. msg.speaker, msg.message, msg.channel, msg.mode,
msg.level)

Here is how should looks code:

function proxy(messages)
for i, msg in ipairs(messages) do
print("proxy: " .. msg.speaker, msg.message, msg.channel, msg.mode,
msg.level)
if msg.message == "Rarity" and msg.mode == 34 then
if msg.speaker == Self.Name() then
Rifbot.PlaySound()
print("Rarity item dropped!")
end
end
end
end
Proxy.New("proxy")

wt., 11 cze 2024 o 18:17 Lewy207 ***@***.***> napisał(a):

**Comment by Lewy207** [comment]
Is not the message , its only on screen detected. But on line is not change rarity for legendary or some like that ?

**Comment by Ascerr** [comment]
You can also use this script, it will search for any keyword in game both
using proxy msg and proxyText:
https://github.com/Ascerr/Lua-Scripts/blob/master/Alert%20on%20keyword%20in%20game.lua

niedz., 7 lip 2024 o 13:27 Lewy207 ***@***.***> napisał(a):

**Comment by Lewy207** [comment]
Thanks a lot, its working :)
