### ISSUE TITLE
Player Step (Alana sio)

### ISSUE THREAD

**Issue by Alkanauts** [Ascerr/Lua-Scripts#3]
Hello, i would like to ask you to make this kind a script. When player/creature in screen it goes inside the house, waits some time, then checks, when player out of screen it says "Alana sio", and continues to make runes. i am ready to support this script.
Thank you for response!

**Comment by Ascerr** [comment]
Hello,

This script will your base:
https://github.com/Ascerr/Lua-Scripts/blob/master/Multifloor%20Player%20Step.lua

Then change line 155 to: Self.Say("alana sio")

Later in line 106 add: Self.Step(dir)

2020-04-05 9:49 GMT+02:00, Alkanauts <notifications@github.com>:
