### ISSUE TITLE
@soft boots changer

### ISSUE THREAD

**Issue by dator35** [Ascerr/Lua-Scripts#5]
The script itself works quite well, but when the script changes from worn soft boots to brand new soft boots, the boots doesnt work, unless the boots slot is empty when you put on the softboots.. Is there any possibility to remove worn soft boots before equipping new pair of soft boots?

**Comment by Ascerr** [comment]
Hello,

Sure it's quite easy to code but tell me "doesnt work" mean bot don't
put new boots or put but boots freeze and don't works?

2021-01-11 15:15 GMT+01:00, dator35 <notifications@github.com>:

**Comment by dator35** [comment]
Well, when you change boots directly from the work soft boots, then the new soft boots doesnt start working - but if boots slot is empty when i put on New soft boots it start working.. 😅

11 jan. 2021 kl. 18:12 skrev Ascerr <notifications@github.com>:

﻿

Hello,

Sure it's quite easy to code but tell me "doesnt work" mean bot don't
put new boots or put but boots freeze and don't works?

2021-01-11 15:15 GMT+01:00, dator35 <notifications@github.com>:

**Comment by Ascerr** [comment]
ok mate i edited script on Github test it.

2021-01-11 23:49 GMT+01:00, dator35 <notifications@github.com>:

**Comment by dator35** [comment]
Nope, still doesnt work .. now it keeps unequipping it
and when its putting a new one immediately - this is how it looks: https://gyazo.com/8d8c03da9163c7e68699bb6729adf8ba

idk maybe just the ot that is fucked up

**Comment by Ascerr** [comment]
If you want send me this softs to character: Night City, town: Thais

I test it and try fix.

2021-01-12 11:26 GMT+01:00, dator35 <notifications@github.com>:

**Comment by dator35** [comment]
9 druid? realera?

**Comment by Ascerr** [comment]
Script attached to this email

**Comment by dator35** [comment]
Okay, so after 4 hours.. this happened: [https://gyazo.com/42cb6f99d43745c0a239bfe8adff30dc.png]
https://gyazo.com/42cb6f99d43745c0a239bfe8adff30dc
it doesnt swap .. id 6530 worn soft boots

________________________________
Från: Ascerr <notifications@github.com>
Skickat: den 12 januari 2021 12:14
Till: Ascerr/Lua-Scripts <Lua-Scripts@noreply.github.com>
Kopia: dator35 <linushimself@live.se>; Author <author@noreply.github.com>
Ämne: Re: [Ascerr/Lua-Scripts] @soft boots changer (#5)


Script attached to this email

**Comment by Ascerr** [comment]
im online and stay in this same place

2021-01-12 16:03 GMT+01:00, dator35 <notifications@github.com>:
