### ISSUE TITLE
Activate Walker on Dmg 

### ISSUE THREAD

**Issue by DelisWTF** [Ascerr/Lua-Scripts#6]
I thinks it would very useful when ur at ur house and anyone attack, it activate Walker and make u to go in house or depot, I try to use the step back on Dmg script but didn't work to me idk why

**Comment by DelisWTF** [comment]
And make Alana sio to go back to make runes

**Comment by Ascerr** [comment]
Hello,

I created script for you to enable walker on dmg:
https://github.com/Ascerr/Lua-Scripts/blob/master/Enable%20Walker%20on%20DGM.lua

Alana sio you can set direct in cavebot example.
-- here you start wpt when someone attack you
node: 23423, 23423, 7
node: 23423, 23423, 7
node: 23423, 23423, 7
node: 23423, 23423, 7
-- here is depot or house and you wait 3min
wait: 180000
-- and here you say alana sio example.
say: alana sio "Your Character Name
-- and you can turn off walker.
state: walker(off)

2021-01-28 7:26 GMT+01:00, DelisWTF <notifications@github.com>:

**Comment by DelisWTF** [comment]
Mate this is gonna change all my days u just make  my day the best in the Month and almost best in the year, tabk you. thank you. thank you so much <3
