### ISSUE TITLE
MEDIVIA 

### ISSUE THREAD

**Issue by DelisWTF** [Ascerr/Lua-Scripts#8]
Excuse me but when will you make an uptodate for Medivia I have lost 2 days of license because I can't open Rifbot with medivia

**Comment by Ascerr** [comment]
Hello,

That was Medivia side problem. They pushed 3 updates in different
hours and was not able to update bot under sleeping.

Please tell me your key, i add 2 days.

2021-04-28 18:10 GMT+02:00, DelisWTF ***@***.***>:
