### ISSUE TITLE
Stop bot when pushed

### ISSUE THREAD

**Issue by DelisWTF** [Ascerr/Lua-Scripts#9]
hello, i think could be very usefull an lua like that, because the're many players pushing us and trying to make reports and its just will looks like we are just afk

**Comment by Ascerr** [comment]
Hello,

You can use this script for alarm when pushed. Just add code after line 23:

Rifbot.setEnabled(false)

https://github.com/Ascerr/Lua-Scripts/blob/master/Alarm%20when%20pushed.lua

2021-05-09 21:29 GMT+02:00, DelisWTF ***@***.***>:
